---
title: ""
author: "Odin Rumianowski"
date: "2024"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache = FALSE)

#wd = "~/These CEFE/Stages/2A - Rieuse - Dynamique La Ronze/3- Plots"
```


```{r}
library(tidyverse)
library(ggplot2)
library(MCMCvis)
library(knitr)
library(patchwork)
library(hrbrthemes)
library(scales)
library(tidyquant)
library(ggthemes)
library(ggdist)
library(ggrepel)
library(patchwork)
```



```{r}
#setwd(wd)

load(file = "data/period_1234/out1_p1_v15_5_p1_4.Rda")
output1= out1
load(file = "data/period_1234/out1_p1_v15_5_p2_4.Rda")
output2= out1
load(file = "data/period_1234/out1_p1_v15_5_p3_4.Rda")
output3= out1
load(file = "data/period_1234/out1_p1_v15_5_p4_4.Rda")
output4= out1
```

```{r}
#setwd(wd)
load(file = "data/period_1234/B_p1_4_2805.Rda")

survey_p1 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VE", "V5", "AE1")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer())


load(file = "data/period_1234/B_p3_4_2805.Rda")

survey_p3 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "AE3")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) 

load(file = "data/period_1234/B_p4_4_2805.Rda")

survey_p4 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "SZ", "AE4")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) %>% 
  subset(year != 2010)

survey = rbind(survey_p1,
               survey_p3,
               survey_p4)

```


```{r}
C1 = output1$samples[[1]]
C2 = output1$samples[[2]]
C3 = output1$samples[[3]]
fit_int_p1 = as.data.frame(rbind(C1, C2, C3))

C1 = output2$samples[[1]]
C2 = output2$samples[[2]]
C3 = output2$samples[[3]]
fit_int_p2 = as.data.frame(rbind(C1, C2, C3))

C1 = output3$samples[[1]]
C2 = output3$samples[[2]]
C3 = output3$samples[[3]]
fit_int_p3 = as.data.frame(rbind(C1, C2, C3))

C1 = output4$samples[[1]]
C2 = output4$samples[[2]]
C3 = output4$samples[[3]]
fit_int_p4 = as.data.frame(rbind(C1, C2, C3))

```

```{r}
col_code_p1 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VE", 
    colonne == 4 ~ "V5", 
    colonne == 5 ~ "AE1"
  )
  return(colonne)
}

col_code_p2 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "AE2"
  )
  return(colonne)
}

col_code_p3 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "AE2"
  )
  return(colonne)
}

col_code_p4 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "SZ", 
    colonne == 8 ~ "AE2"
  )
  return(colonne)
}
```



# Dispersion

```{r}

df_fid_1 = data.frame(natalfidelity = output1$mean$natalfidelity,
                 breedingfidelity = output1$mean$breedingfidelity,
                 mean_B = output1$mean$B %>% rowMeans(),
                 colony = c("LR", "MA", "VE", "V5", "AE1"),
                 Period = rep("1", 5)
) %>% 
  subset(., colony != "AE1")

df_fid_2 = data.frame(natalfidelity = output3$mean$natalfidelity,
                 breedingfidelity = output3$mean$breedingfidelity,
                 mean_B = output3$mean$B %>% rowMeans(),
                 colony = c("LR", "MA", "VS", "LA","SV", "WV", "AE2"),
                 Period = rep("2", 7)
)%>% 
  subset(., colony != "AE2")

df_fid_3 = data.frame(natalfidelity = output4$mean$natalfidelity,
                 breedingfidelity = output4$mean$breedingfidelity,
                 mean_B = output4$mean$B %>% rowMeans(),
                 colony = c("LR", "MA", "VS", "LA","SV", "WV", "SZ", "AE2"),
                 Period = rep("3", 8)
)%>% 
  subset(., colony != "AE2")

df_fid = rbind(df_fid_1,
               df_fid_3)

```



## Natal dispersion

```{r}
#P1
n.colony_p1 = 5
fit_int_p1_ = fit_int_p1 %>% 
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`, `natalfidelity[5]`) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%   # AJOUT KG
  mutate(colony_Period = case_when(
    param == "natalfidelity[1]" ~ "LR_p1", 
    param == "natalfidelity[2]" ~ "MA_p1", 
    param == "natalfidelity[3]" ~ "VE_p1", 
    param == "natalfidelity[4]" ~ "V5_p1", 
    param == "natalfidelity[5]" ~ "AE_p1"))

fit_int_p1_ = fit_int_p1_ %>% 
  subset(., colony_Period != "AE_p1")

colony_size_p1 = output1$mean$B %>% rowMeans()
colony_size_p1 = colony_size_p1[1:(n.colony_p1-1)]

fit_int_p1_ = fit_int_p1_ %>% 
  mutate(Period = rep("1987-2006", nrow(fit_int_p1_)))%>% 
  mutate(colony_size = rep(colony_size_p1, nrow(fit_int_p1_)/(n.colony_p1-1)))


#P3
n.colony_p3 = 7
fit_int_p3_ = fit_int_p3 %>% 
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`,
         `natalfidelity[5]`, `natalfidelity[6]`, `natalfidelity[7]`) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%   # AJOUT KG 
  mutate(colony_Period = case_when(
    param == "natalfidelity[1]" ~ "LR_p3", 
    param == "natalfidelity[2]" ~ "MA_p3", 
    param == "natalfidelity[3]" ~ "VS_p3", 
    param == "natalfidelity[4]" ~ "LA_p3", 
    param == "natalfidelity[5]" ~ "SV_p3", 
    param == "natalfidelity[6]" ~ "WV_p3", 
    param == "natalfidelity[7]" ~ "AE_p3"))

fit_int_p3_ = fit_int_p3_ %>% 
  subset(., colony_Period != "AE_p3")

colony_size_p3 = output3$mean$B %>% rowMeans()
colony_size_p3 = colony_size_p3[1:(n.colony_p3-1)]

fit_int_p3_ = fit_int_p3_ %>% 
  mutate(Period = rep("2007-2010", nrow(fit_int_p3_)))%>% 
  mutate(colony_size = rep(colony_size_p3, nrow(fit_int_p3_)/(n.colony_p3-1)))

#P4
n.colony_p4 = 8
fit_int_p4_ = fit_int_p4 %>% 
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`,
         `natalfidelity[5]`, `natalfidelity[6]`, `natalfidelity[7]`, `natalfidelity[8]`,) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%   # AJOUT KG 
  mutate(colony_Period = case_when(
    param == "natalfidelity[1]" ~ "LR_p4", 
    param == "natalfidelity[2]" ~ "MA_p4", 
    param == "natalfidelity[3]" ~ "VS_p4", 
    param == "natalfidelity[4]" ~ "LA_p4", 
    param == "natalfidelity[5]" ~ "SV_p4", 
    param == "natalfidelity[6]" ~ "WV_p4", 
    param == "natalfidelity[7]" ~ "SZ_p4", 
    param == "natalfidelity[8]" ~ "AE_p4"))

fit_int_p4_ = fit_int_p4_ %>% 
  subset(., colony_Period != "AE_p4")

colony_size_p4 = output4$mean$B %>% rowMeans()
colony_size_p4 = colony_size_p4[1:(n.colony_p4-1)]

fit_int_p4_ = fit_int_p4_ %>% 
  mutate(Period = rep("2010-2019", nrow(fit_int_p4_)))%>% 
  mutate(colony_size = rep(colony_size_p4, nrow(fit_int_p4_)/(n.colony_p4-1)))

natal_fidelity = rbind(fit_int_p1_,
                       #fit_int_p3_, 
                       fit_int_p4_)
```





### Correlation natal fidelity - mean colony size
```{r}
## mean_B:
mean_B.1 = fit_int_p1 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 1) |> 
  relocate(Period, .before = iteration)

mean_B.3 = fit_int_p3 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 3) |> 
  relocate(Period, .before = iteration)

mean_B.4 = fit_int_p4 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 4) |> 
  relocate(Period, .before = iteration)

mean_B = bind_rows(mean_B.1, mean_B.3, mean_B.4) |> 
  # Add columns with indexes of the original matrix (colony & year):
  mutate(col_year = gsub("B[", "", param, fixed = T),
         col_year = gsub("]", "", col_year, fixed = T)) |> 
  separate_wider_delim(col_year, names = c("col", "year"), delim = ",") |> 
  mutate(col = as.numeric(col),
         year = as.numeric(year)) |> 
  arrange(Period, iteration, col, year) |> 
  # Get mean colony size on the Period for each iteration:
  group_by(Period, iteration, col) |> 
  summarise(mean_B = mean(value)) |> 
  # Change names for compatibility with "natal_fidelity" table:
    mutate(col = as.character(col),
         col = ifelse(Period == 1 & col == "1", "LR_p1", col),
         col = ifelse(Period == 1 & col == "2", "MA_p1", col),
         col = ifelse(Period == 1 & col == "3", "VE_p1", col),
         col = ifelse(Period == 1 & col == "4", "V5_p1", col),
         col = ifelse(Period == 1 & col == "5", "AE_p1", col),
         col = ifelse(Period == 3 & col == "1", "LR_p3", col),
         col = ifelse(Period == 3 & col == "2", "MA_p3", col),
         col = ifelse(Period == 3 & col == "3", "VS_p3", col),
         col = ifelse(Period == 3 & col == "4", "LA_p3", col),
         col = ifelse(Period == 3 & col == "5", "SV_p3", col),
         col = ifelse(Period == 3 & col == "6", "WV_p3", col),
         col = ifelse(Period == 3 & col == "7", "AE_p3", col),
         col = ifelse(Period == 4 & col == "1", "LR_p4", col),
         col = ifelse(Period == 4 & col == "2", "MA_p4", col),
         col = ifelse(Period == 4 & col == "3", "VS_p4", col),
         col = ifelse(Period == 4 & col == "4", "LA_p4", col),
         col = ifelse(Period == 4 & col == "5", "SV_p4", col),
         col = ifelse(Period == 4 & col == "6", "WV_p4", col),
         col = ifelse(Period == 4 & col == "7", "SZ_p4", col),
         col = ifelse(Period == 4 & col == "8", "AE_p4", col)) |> 
  mutate(Period = as.character(Period),
         Period = ifelse(Period == "1", "1987-2006", Period),
         Period = ifelse(Period == "3", "2007-2010", Period),
         Period = ifelse(Period == "4", "2010-2019", Period))



## Fidelity:
corr.natal_fidelity = natal_fidelity %>%
  # Join estimates for mean_B on the colony:
  mutate(iteration = as.numeric(iteration)) |> 
  left_join(mean_B, by = c("Period", "iteration", "colony_Period" = "col")) |> 
  # Calculate correlation between settlement probabilities and mean colony size on the Period:
  group_by(Period, iteration) %>%
  mutate(corr = cor.test(x = value, y = mean_B, method = "spearman")$estimate[[1]]) %>%
  group_by(Period) %>%
  summarise(corr.med = mean(corr),
            corr.inf = quantile(corr, probs = 0.025),
            corr.sup = quantile(corr, probs = 0.975))

my_natal_fidelity = natal_fidelity %>% 
  select(iteration, colony_Period,value, Period) %>% 
  mutate(type = "natal")
```


```{r}
plot.corr.natal_fidelity = ggplot() +
  geom_hline(aes(yintercept = 0), linetype = "dashed", colour = "grey50", linewidth = 1) +
  geom_point(data = corr.natal_fidelity, aes(x = Period, y = corr.med)) +
  geom_linerange(data = corr.natal_fidelity, aes(x = Period, ymin = corr.inf, ymax = corr.sup)) +
  geom_label_repel(data = corr.natal_fidelity, aes(x = Period, y = corr.med, 
                              label = paste0(round(corr.med,2), " [", round(corr.inf,2), ", ", round(corr.sup,2), "]"))) +
  labs(x = "", y = "Correlation Natal Fidelity - Mean colony size") +
  theme_classic()
```


```{r}
plot.corr.natal_fidelity
```


```{r}
# ggsave(plot.corr.natal_fidelity, filename = "plot.corr.natal_fidelity.png",
#        dpi = 600, width = 16, height = 12, units = "cm")
```




## Breeding dispersion

```{r}
#natal fidelity
#P1
n.colony_p1 = 5
fit_int_p1_ = fit_int_p1 %>% 
  select(`breedingfidelity[1]`, `breedingfidelity[2]`, `breedingfidelity[3]`, `breedingfidelity[4]`, `breedingfidelity[5]`) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%    # AJOUT KG
  mutate(colony_Period = case_when(
    param == "breedingfidelity[1]" ~ "LR_p1", 
    param == "breedingfidelity[2]" ~ "MA_p1", 
    param == "breedingfidelity[3]" ~ "VE_p1", 
    param == "breedingfidelity[4]" ~ "V5_p1", 
    param == "breedingfidelity[5]" ~ "AE_p1"))

fit_int_p1_ = fit_int_p1_ %>% 
  subset(., colony_Period != "AE_p1")

colony_size_p1 = output1$mean$B %>% rowMeans()
colony_size_p1 = colony_size_p1[1:(n.colony_p1-1)]

fit_int_p1_ = fit_int_p1_ %>% 
  mutate(Period = rep("1987-2006", nrow(fit_int_p1_)))%>% 
  mutate(colony_size = rep(colony_size_p1, nrow(fit_int_p1_)/(n.colony_p1-1)))


#P3
n.colony_p3 = 7
fit_int_p3_ = fit_int_p3 %>% 
  select(`breedingfidelity[1]`, `breedingfidelity[2]`, `breedingfidelity[3]`, `breedingfidelity[4]`,
         `breedingfidelity[5]`, `breedingfidelity[6]`, `breedingfidelity[7]`) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%    # AJOUT KG
  mutate(colony_Period = case_when(
    param == "breedingfidelity[1]" ~ "LR_p3", 
    param == "breedingfidelity[2]" ~ "MA_p3", 
    param == "breedingfidelity[3]" ~ "VS_p3", 
    param == "breedingfidelity[4]" ~ "LA_p3", 
    param == "breedingfidelity[5]" ~ "SV_p3", 
    param == "breedingfidelity[6]" ~ "WV_p3", 
    param == "breedingfidelity[7]" ~ "AE_p3"))

fit_int_p3_ = fit_int_p3_ %>% 
  subset(., colony_Period != "AE_p3")

colony_size_p3 = output3$mean$B %>% rowMeans()
colony_size_p3 = colony_size_p3[1:(n.colony_p3-1)]

fit_int_p3_ = fit_int_p3_ %>% 
  mutate(Period = rep("2007-2010", nrow(fit_int_p3_)))%>% 
  mutate(colony_size = rep(colony_size_p3, nrow(fit_int_p3_)/(n.colony_p3-1)))

#P4
n.colony_p4 = 8
fit_int_p4_ = fit_int_p4 %>% 
  select(`breedingfidelity[1]`, `breedingfidelity[2]`, `breedingfidelity[3]`, `breedingfidelity[4]`,
         `breedingfidelity[5]`, `breedingfidelity[6]`, `breedingfidelity[7]`, `breedingfidelity[8]`,) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%    # AJOUT KG
  mutate(colony_Period = case_when(
    param == "breedingfidelity[1]" ~ "LR_p4", 
    param == "breedingfidelity[2]" ~ "MA_p4", 
    param == "breedingfidelity[3]" ~ "VS_p4", 
    param == "breedingfidelity[4]" ~ "LA_p4", 
    param == "breedingfidelity[5]" ~ "SV_p4", 
    param == "breedingfidelity[6]" ~ "WV_p4", 
    param == "breedingfidelity[7]" ~ "SZ_p4", 
    param == "breedingfidelity[8]" ~ "AE_p4"))

fit_int_p4_ = fit_int_p4_ %>% 
  subset(., colony_Period != "AE_p4")

colony_size_p4 = output4$mean$B %>% rowMeans()
colony_size_p4 = colony_size_p4[1:(n.colony_p4-1)]

fit_int_p4_ = fit_int_p4_ %>% 
  mutate(Period = rep("2010-2019", nrow(fit_int_p4_)))%>% 
  mutate(colony_size = rep(colony_size_p4, nrow(fit_int_p4_)/(n.colony_p4-1)))

breeding_fidelity = rbind(fit_int_p1_,
                          fit_int_p4_)
```





###  Correlation breeding fidelity - mean colony size
```{r}
## mean_B:
mean_B.1 = fit_int_p1 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 1) |> 
  relocate(Period, .before = iteration)

mean_B.3 = fit_int_p3 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 3) |> 
  relocate(Period, .before = iteration)

mean_B.4 = fit_int_p4 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 4) |> 
  relocate(Period, .before = iteration)

mean_B = bind_rows(mean_B.1, mean_B.3, mean_B.4) |> 
  # Add columns with indexes of the original matrix (colony & year):
  mutate(col_year = gsub("B[", "", param, fixed = T),
         col_year = gsub("]", "", col_year, fixed = T)) |> 
  separate_wider_delim(col_year, names = c("col", "year"), delim = ",") |> 
  mutate(col = as.numeric(col),
         year = as.numeric(year)) |> 
  arrange(Period, iteration, col, year) |> 
  # Get mean colony size on the Period for each iteration:
  group_by(Period, iteration, col) |> 
  summarise(mean_B = mean(value)) |> 
  # Change names for compatibility with "natal_fidelity" table:
    mutate(col = as.character(col),
         col = ifelse(Period == 1 & col == "1", "LR_p1", col),
         col = ifelse(Period == 1 & col == "2", "MA_p1", col),
         col = ifelse(Period == 1 & col == "3", "VE_p1", col),
         col = ifelse(Period == 1 & col == "4", "V5_p1", col),
         col = ifelse(Period == 1 & col == "5", "AE_p1", col),
         col = ifelse(Period == 3 & col == "1", "LR_p3", col),
         col = ifelse(Period == 3 & col == "2", "MA_p3", col),
         col = ifelse(Period == 3 & col == "3", "VS_p3", col),
         col = ifelse(Period == 3 & col == "4", "LA_p3", col),
         col = ifelse(Period == 3 & col == "5", "SV_p3", col),
         col = ifelse(Period == 3 & col == "6", "WV_p3", col),
         col = ifelse(Period == 3 & col == "7", "AE_p3", col),
         col = ifelse(Period == 4 & col == "1", "LR_p4", col),
         col = ifelse(Period == 4 & col == "2", "MA_p4", col),
         col = ifelse(Period == 4 & col == "3", "VS_p4", col),
         col = ifelse(Period == 4 & col == "4", "LA_p4", col),
         col = ifelse(Period == 4 & col == "5", "SV_p4", col),
         col = ifelse(Period == 4 & col == "6", "WV_p4", col),
         col = ifelse(Period == 4 & col == "7", "SZ_p4", col),
         col = ifelse(Period == 4 & col == "8", "AE_p4", col)) |> 
  mutate(Period = as.character(Period),
         Period = ifelse(Period == "1", "1987-2006", Period),
         Period = ifelse(Period == "3", "2007-2010", Period),
         Period = ifelse(Period == "4", "2010-2019", Period))



## Fidelity:
corr.breeding_fidelity = breeding_fidelity %>%
  # Join estimates for mean_B on the colony:
  mutate(iteration = as.numeric(iteration)) |> 
  left_join(mean_B, by = c("Period", "iteration", "colony_Period" = "col")) |> 
  # Calculate correlation between settlement probabilities and mean colony size on the Period:
  group_by(Period, iteration) %>%
  mutate(corr = cor.test(x = value, y = mean_B, method = "spearman")$estimate[[1]]) %>%
  group_by(Period) %>%
  summarise(corr.med = mean(corr),
            corr.inf = quantile(corr, probs = 0.025),
            corr.sup = quantile(corr, probs = 0.975))


my_breeding_fidelity = breeding_fidelity %>% 
  select(iteration, colony_Period, value, Period) %>% 
  mutate(type = "breeding")

plot.corr.breeding_fidelity = ggplot() +
  geom_hline(aes(yintercept = 0), linetype = "dashed", colour = "grey50", linewidth = 1) +
  geom_point(data = corr.breeding_fidelity, aes(x = Period, y = corr.med)) +
  geom_linerange(data = corr.breeding_fidelity, aes(x = Period, ymin = corr.inf, ymax = corr.sup)) +
  geom_label_repel(data = corr.breeding_fidelity, aes(x = Period, y = corr.med, 
                              label = paste0(round(corr.med,2), " [", round(corr.inf,2), ", ", round(corr.sup,2), "]"))) +
  labs(x = "", y = "Correlation Breeding Fidelity - Mean colony size") +
  theme_classic()
```


```{r}
plot.corr.breeding_fidelity
```


```{r}
# ggsave(plot.corr.breeding_fidelity, filename = "plot.corr.breeding_fidelity.png",
#        dpi = 600, width = 16, height = 12, units = "cm")
```




```{r}

corr.fidelity = merge(my_breeding_fidelity, my_natal_fidelity, by=c("iteration", "colony_Period")) %>% 
  rename(breeding_fidelity = value.x,
         natal_fidelity = value.y,
         Period = Period.x) %>% 
  select(iteration, breeding_fidelity, natal_fidelity, Period)


corr.fidelity_p1 = corr.fidelity %>%
  subset(Period == "1987-2006") %>% 
  # Join estimates for mean_B on the colony:
  mutate(iteration = as.numeric(iteration)) |> 
  # Calculate correlation between settlement probabilities and mean colony size on the Period:
  group_by(iteration) %>%
  mutate(corr = cor.test(x = natal_fidelity, y = breeding_fidelity, method = "spearman")$estimate[[1]]) %>% 
  ungroup()%>%
  summarise(corr.med = mean(corr),
            corr.inf = quantile(corr, probs = 0.025),
            corr.sup = quantile(corr, probs = 0.975))

corr.fidelity_p4 = corr.fidelity %>%
  subset(Period == "2010-2019") %>% 
  # Join estimates for mean_B on the colony:
  mutate(iteration = as.numeric(iteration)) |> 
  # Calculate correlation between settlement probabilities and mean colony size on the Period:
  group_by(iteration) %>%
  mutate(corr = cor.test(x = natal_fidelity, y = breeding_fidelity, method = "spearman")$estimate[[1]]) %>% 
  ungroup()%>%
  summarise(corr.med = mean(corr),
            corr.inf = quantile(corr, probs = 0.025),
            corr.sup = quantile(corr, probs = 0.975))
```













