---
title: ""
author: "Odin Rumianowski"
date: "2024"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
---

 
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache = FALSE)

#wd = "~/These CEFE/Stages/2A - Rieuse - Dynamique La Ronze/3- Plots"
```


```{r}
library(tidyverse)
library(ggplot2)
library(MCMCvis)
library(knitr)
library(patchwork)
library(hrbrthemes)
library(scales)
library(tidyquant)
library(ggthemes)
library(ggdist)
library(ggrepel)
library(patchwork)
```



```{r}
#setwd(wd)

load(file = "data/period_1234/out1_p1_v15_5_p1_4.Rda")
output1= out1
load(file = "data/period_1234/out1_p1_v15_5_p2_4.Rda")
output2= out1
load(file = "data/period_1234/out1_p1_v15_5_p3_4.Rda")
output3= out1
load(file = "data/period_1234/out1_p1_v15_5_p4_4.Rda")
output4= out1
```

```{r}
C1 = output1$samples[[1]]
C2 = output1$samples[[2]]
C3 = output1$samples[[3]]
fit_int_p1 = as.data.frame(rbind(C1, C2, C3))

C1 = output2$samples[[1]]
C2 = output2$samples[[2]]
C3 = output2$samples[[3]]
fit_int_p2 = as.data.frame(rbind(C1, C2, C3))

C1 = output3$samples[[1]]
C2 = output3$samples[[2]]
C3 = output3$samples[[3]]
fit_int_p3 = as.data.frame(rbind(C1, C2, C3))

C1 = output4$samples[[1]]
C2 = output4$samples[[2]]
C3 = output4$samples[[3]]
fit_int_p4 = as.data.frame(rbind(C1, C2, C3))

```

# Settlement

## Natal 

```{r}

settlement = output1$mean$eta
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:5)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:5, 5)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 5)%>% 
  subset(., arr != 5)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output1$mean$B %>% rowMeans(),
                 arr = 1:5)

settlement1 = merge(settlement, col_size, by = c("arr"))%>% 
  mutate(Period = "1")

```

```{r}

settlement = output3$mean$eta
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:7)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:7, 7)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 7)%>% 
  subset(., arr != 7)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output3$mean$B %>% rowMeans(),
                 arr = 1:7)

settlement3 = merge(settlement, col_size, by = c("arr")) %>% 
  mutate(Period = "3")

```

```{r}

settlement = output4$mean$eta
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:8)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:8, 8)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 8)%>% 
  subset(., arr != 8)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output4$mean$B %>% rowMeans(),
                 arr = 1:8)

settlement4 = merge(settlement, col_size, by = c("arr")) %>% 
  mutate(Period = "4")

```


```{r}
settlement = rbind(settlement1,
                   settlement3,
                   settlement4)
```







###  Correlation natal settlement - mean colony size
```{r}
## mean_B:
mean_B.1 = fit_int_p1 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 1) |> 
  relocate(Period, .before = iteration)

mean_B.3 = fit_int_p3 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 3) |> 
  relocate(Period, .before = iteration)

mean_B.4 = fit_int_p4 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 4) |> 
  relocate(Period, .before = iteration)

mean_B = bind_rows(mean_B.1, mean_B.3, mean_B.4) |> 
  # Add columns with indexes of the original matrix (colony & year):
  mutate(col_year = gsub("B[", "", param, fixed = T),
         col_year = gsub("]", "", col_year, fixed = T)) |> 
  separate_wider_delim(col_year, names = c("col", "year"), delim = ",") |> 
  mutate(col = as.numeric(col),
         year = as.numeric(year)) |> 
  arrange(Period, iteration, col, year) |> 
  # Get mean colony size on the Period for each iteration:
  group_by(Period, iteration, col) |> 
  summarise(mean_B = mean(value))



## Settlement:
nat_set.1 = fit_int_p1 |> 
  select(starts_with("eta[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 1) |> 
  relocate(Period, .before = iteration)

nat_set.3 = fit_int_p3 |> 
  select(starts_with("eta[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 3) |> 
  relocate(Period, .before = iteration)

nat_set.4 = fit_int_p4 |> 
  select(starts_with("eta[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 4) |> 
  relocate(Period, .before = iteration)

nat_set = bind_rows(nat_set.1, nat_set.3, nat_set.4) |> 
  # Add columns with indexes of the original matrix (departure & arrival):
  mutate(dep_arr = gsub("eta[", "", param, fixed = T),
         dep_arr = gsub("]", "", dep_arr, fixed = T)) |> 
  separate_wider_delim(dep_arr, names = c("dep", "arr"), delim = ",") |> 
  mutate(dep = as.numeric(dep),
         arr = as.numeric(arr)) |> 
  arrange(Period, iteration, dep, arr) |> 
  # Remove fidelity:
  filter(dep != arr) |> 
  # Normalise for each departure (sum to 1):
  group_by(Period, iteration, dep) |> 
  mutate(value_norm = value/sum(value)) |> 
  # Remove AE for each Period:
  group_by(Period, iteration) |> 
  filter(dep != max(dep) & arr != max(arr)) |> 
  # Join estimates for mean_B on the colony of arrival:
  left_join(mean_B, by = c("Period", "iteration", "arr" = "col")) |> 
  mutate(Period = as.character(Period),
         Period = ifelse(Period == "1", "1987-2006", Period),
         Period = ifelse(Period == "3", "2007-2010", Period),
         Period = ifelse(Period == "4", "2010-2019", Period))
  
corr.nat_set = nat_set |> 
  # Calculate correlation between settlement probabilities and mean colony size on the Period:
  group_by(Period, iteration) |> 
  mutate(corr = cor.test(x = value_norm, y = mean_B, method = "spearman")$estimate[[1]]) |> 
  group_by(Period) |> 
  summarise(corr.med = mean(corr),
            corr.inf = quantile(corr, probs = 0.025),
            corr.sup = quantile(corr, probs = 0.975))

plot.corr.nat_set = ggplot() +
  geom_hline(aes(yintercept = 0), linetype = "dashed", colour = "grey50", linewidth = 1) +
  geom_point(data = corr.nat_set, aes(x = Period, y = corr.med)) +
  geom_linerange(data = corr.nat_set, aes(x = Period, ymin = corr.inf, ymax = corr.sup)) +
  geom_label_repel(data = corr.nat_set, aes(x = Period, y = corr.med, 
                              label = paste0(round(corr.med,2), " [", round(corr.inf,2), ", ", round(corr.sup,2), "]"))) +
  labs(x = "", y = "Correlation Natal Settlement - Mean colony size") +
  theme_classic()

plot.corr.nat_set

# ggsave(plot.corr.nat_set, filename = "plot.corr.nat_set.png",
#        dpi = 600, width = 16, height = 12, units = "cm")

rm(list = c("mean_B.1", "mean_B.3", "mean_B.4", "nat_set.1", "nat_set.3", "nat_set.4"))
```

###  Distribution breeding settlement
```{r}
sd.breed_set = settlement %>%  
  mutate(dep_type = ifelse(dep == 1, "LR", "Satellite")) %>% 
  subset(dep != 1) %>% 
  mutate(arr = as.integer(arr)) %>% 
  mutate(arr_type = ifelse(arr == 1, "LR", "Satellite")) %>% 
  mutate(Period = as.character(Period),
         Period = ifelse(Period == "1", "1986-2006", Period),
         Period = ifelse(Period == "3", "2007-2010", Period),
         Period = ifelse(Period == "4", "2010-2019", Period))
```







## Breeding

```{r}

settlement = output1$mean$nu
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:5)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:5, 5)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 5)%>% 
  subset(., arr != 5)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output1$mean$B %>% rowMeans(),
                 arr = 1:5)

settlement1 = merge(settlement, col_size, by = c("arr"))%>% 
  mutate(Period = "1")

```

```{r}

settlement = output3$mean$nu
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:7)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:7, 7)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 7)%>% 
  subset(., arr != 7)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output3$mean$B %>% rowMeans(),
                 arr = 1:7)

settlement3 = merge(settlement, col_size, by = c("arr")) %>% 
  mutate(Period = "3")

```

```{r}

settlement = output4$mean$nu
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:8)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:8, 8)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 8)%>% 
  subset(., arr != 8)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output4$mean$B %>% rowMeans(),
                 arr = 1:8)

settlement4 = merge(settlement, col_size, by = c("arr")) %>% 
  mutate(Period = "4")

```


```{r}
settlement = rbind(settlement1,
                   settlement3,
                   settlement4)
```





###  Correlation breeding settlement - mean colony size
```{r}
## mean_B:
mean_B.1 = fit_int_p1 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 1) |> 
  relocate(Period, .before = iteration)

mean_B.3 = fit_int_p3 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 3) |> 
  relocate(Period, .before = iteration)

mean_B.4 = fit_int_p4 |> 
  select(starts_with("B[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 4) |> 
  relocate(Period, .before = iteration)

mean_B = bind_rows(mean_B.1, mean_B.3, mean_B.4) |> 
  # Add columns with indexes of the original matrix (colony & year):
  mutate(col_year = gsub("B[", "", param, fixed = T),
         col_year = gsub("]", "", col_year, fixed = T)) |> 
  separate_wider_delim(col_year, names = c("col", "year"), delim = ",") |> 
  mutate(col = as.numeric(col),
         year = as.numeric(year)) |> 
  arrange(Period, iteration, col, year) |> 
  # Get mean colony size on the Period for each iteration:
  group_by(Period, iteration, col) |> 
  summarise(mean_B = mean(value))



## Settlement:
breed_set.1 = fit_int_p1 |> 
  select(starts_with("nu[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 1) |> 
  relocate(Period, .before = iteration)

breed_set.3 = fit_int_p3 |> 
  select(starts_with("nu[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 3) |> 
  relocate(Period, .before = iteration)

breed_set.4 = fit_int_p4 |> 
  select(starts_with("nu[")) |> 
  rownames_to_column("iteration") |> 
  pivot_longer(!iteration, names_to = "param", values_to = "value") |> 
  mutate(iteration = as.numeric(iteration),
         Period = 4) |> 
  relocate(Period, .before = iteration)

breed_set = bind_rows(breed_set.1, breed_set.3, breed_set.4) |> 
  # Add columns with indexes of the original matrix (departure & arrival):
  mutate(dep_arr = gsub("nu[", "", param, fixed = T),
         dep_arr = gsub("]", "", dep_arr, fixed = T)) |> 
  separate_wider_delim(dep_arr, names = c("dep", "arr"), delim = ",") |> 
  mutate(dep = as.numeric(dep),
         arr = as.numeric(arr)) |> 
  arrange(Period, iteration, dep, arr) |> 
  # Remove fidelity:
  filter(dep != arr) |> 
  # Normalise for each departure (sum to 1):
  group_by(Period, iteration, dep) |> 
  mutate(value_norm = value/sum(value)) |> 
  # Remove AE for each Period:
  group_by(Period, iteration) |> 
  filter(dep != max(dep) & arr != max(arr)) |> 
  # Join estimates for mean_B on the colony of arrival:
  left_join(mean_B, by = c("Period", "iteration", "arr" = "col")) |> 
  mutate(Period = as.character(Period),
         Period = ifelse(Period == "1", "1987-2006", Period),
         Period = ifelse(Period == "3", "2007-2010", Period),
         Period = ifelse(Period == "4", "2010-2019", Period))
  
corr.breed_set = breed_set |> 
  # Calculate correlation between settlement probabilities and mean colony size on the Period:
  group_by(Period, iteration) |> 
  mutate(corr = cor.test(x = value_norm, y = mean_B, method = "spearman")$estimate[[1]]) |> 
  group_by(Period) |> 
  summarise(corr.med = mean(corr),
            corr.inf = quantile(corr, probs = 0.025),
            corr.sup = quantile(corr, probs = 0.975))

plot.corr.breed_set = ggplot() +
  geom_hline(aes(yintercept = 0), linetype = "dashed", colour = "grey50", linewidth = 1) +
  geom_point(data = corr.breed_set, aes(x = Period, y = corr.med)) +
  geom_linerange(data = corr.breed_set, aes(x = Period, ymin = corr.inf, ymax = corr.sup)) +
  geom_label_repel(data = corr.breed_set, aes(x = Period, y = corr.med, 
                              label = paste0(round(corr.med,2), " [", round(corr.inf,2), ", ", round(corr.sup,2), "]"))) +
  labs(x = "", y = "Correlation Breeding Settlement - Mean colony size") +
  theme_classic()
```


```{r}
plot.corr.breed_set
```


```{r}
# ggsave(plot.corr.breed_set, filename = "plot.corr.breed_set.png",
#        dpi = 600, width = 16, height = 12, units = "cm")

```

