---
title: "Data summary"
author: "Odin Rumianowski"
date: "2024-05-12"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r}
load(file = "data/period_1234/CH_p123_0905.Rda")
```



```{r,cache = TRUE}
n.colony = 10

effort = CH %>% 
  as_tibble() %>% 
  pivot_longer(everything()) %>% 
  mutate(value = as.factor(value)) %>% 
  group_by(name, value) %>% 
  count() %>% 
  mutate(name = as.numeric(stringr::str_extract(name, "\\d+"))) %>% 
  arrange(name) %>% 
  pivot_wider(names_from = name, values_from = n) %>% 
  arrange(., value)

effort[is.na(effort)] = 0

```

```{r}

ringing_effort = effort %>%
  ungroup() %>% 
  slice(2:(n.colony+1)) %>% 
  select(-1) %>% 
  as.matrix()

ringing_effort_total = cbind(
                       rowSums(ringing_effort[,1:21]),
                       rowSums(ringing_effort[,22:25]),
                       rowSums(ringing_effort[,26:34]),
                       rowSums(ringing_effort))


ringing_effort = cbind(ringing_effort,
                       ringing_effort_total)

colnames(ringing_effort) = c(1986:2019, "Period 1", "Period 2", "Period 3", "Total")

ringing_effort = rbind(ringing_effort,
                       colSums(ringing_effort))

rownames(ringing_effort)  = c(1:10, "Total")          



```

```{r}

reading_effort = effort %>%
  ungroup() %>% 
  slice(c((n.colony+2):(2*n.colony))) %>% 
  select(-1) %>% 
  as.matrix()

reading_effort_total = cbind(
                       rowSums(reading_effort[,1:21]),
                       rowSums(reading_effort[,22:25]),
                       rowSums(reading_effort[,26:34]),
                       rowSums(reading_effort))

reading_effort = cbind(reading_effort,
                       reading_effort_total)

colnames(reading_effort) = c(1986:2019, "Period 1", "Period 2", "Period 3", "Total")

reading_effort = rbind(reading_effort,
                       colSums(reading_effort))

rownames(reading_effort)  = c(1:9, "Total")          


```



```{r}
reading_effort_total = rbind(reading_effort_total,matrix(0, nrow = 1, ncol = 4))
```


```{r}
effort_total = cbind(ringing_effort_total,
                     reading_effort_total)

effort_total = rbind(effort_total, colSums(effort_total))

colnames(effort_total) = c("1986-2006", "2007-2010", "2011-2019", "1986-2019",
                           "1986-2006", "2007-2010", "2011-2019", "1986-2019")

rownames(effort_total) = c("LR", "MA", "VE", "V5", 
                           "VS", "LA","SV", "WV", "SZ",
                           "AE",
                           "Total")
```

```{r}
effort_total = effort_total %>% 
 kbl(.,longtable=T,booktabs=T,caption="Summary - CMR dataset") %>%
 add_header_above(c("" ,"Ringing effort" = 4 ,"Reading effort" = 4)) %>%
 kable_styling(latex_options=c("striped","scale_down")) %>%
 column_spec(c(1, 5, 9), bold = T) 
```

```{r}

codification = data.frame(Colony = c("La Ronze", "Les Marquants", "La Verchère", "Vallon #5",
                                     "La Vergnat Sud",
                      "Les Champs Blancs", "Sury", "Vieux Ouest",
                      "La Sausée", "Alive Elsewhere"),
           Code = c("LR", "MA", "VE", "V5", "VS", "LA","SV", "WV", "SZ","AE"),
           Nestling = 1:10,
           Breeder = 11:20,
           Prebreeder = 21:30)

```

```{r}
codification = codification %>% 
 kbl(.,longtable=T,booktabs=T,caption="Codification") %>%
 add_header_above(c("" ,"", "Reproduction Class" = 3)) %>%
 kable_styling(latex_options=c("striped","scale_down")) 
```

```{r}
sigma_table = data.frame(hh = c("La Ronze","Other colonies"),
                         p1 = c("Method 1","Method 3"),
                         p2 = c("Method 2","Method 3"),
                         p3 = c("Method 3","Method 3"))

colnames(sigma_table) = c("", "1986-2000", "2000-2006", "2007-2019")

sigma_table = sigma_table %>% 
 kbl(.,longtable=T,booktabs=T,caption="Method of count") %>%
 add_header_above(c("", "Period" = 3)) %>%
 kable_styling(latex_options=c("scale_down")) 


```


```{r}
codification
```

```{r}
effort_total
```



