---
title: ""
author: "Odin Rumianowski"
date: "2024"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache = FALSE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(MCMCvis)
library(knitr)
library(patchwork)
library(hrbrthemes)
library(scales)
library(tidyquant)
library(ggthemes)
library(ggdist)
library(ggrepel)
library(patchwork)
```



```{r}
#setwd(wd)

load(file = "data/period_1234/out1_p1_v15_5_p1_4.Rda")
output1= out1
load(file = "data/period_1234/out1_p1_v15_5_p2_4.Rda")
output2= out1
load(file = "data/period_1234/out1_p1_v15_5_p3_4.Rda")
output3= out1
load(file = "data/period_1234/out1_p1_v15_5_p4_4.Rda")
output4= out1
```

```{r}
#setwd(wd)
load(file = "data/period_1234/B_p1_4_2805.Rda")

survey_p1 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VE", "V5", "AE1")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer())


load(file = "data/period_1234/B_p3_4_2805.Rda")

survey_p3 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "AE3")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) 

load(file = "data/period_1234/B_p4_4_2805.Rda")

survey_p4 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "SZ", "AE4")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) %>% 
  subset(year != 2010)

survey = rbind(survey_p1,
               survey_p3,
               survey_p4)

```


```{r}
C1 = output1$samples[[1]]
C2 = output1$samples[[2]]
C3 = output1$samples[[3]]
fit_int_p1 = as.data.frame(rbind(C1, C2, C3))

C1 = output2$samples[[1]]
C2 = output2$samples[[2]]
C3 = output2$samples[[3]]
fit_int_p2 = as.data.frame(rbind(C1, C2, C3))

C1 = output3$samples[[1]]
C2 = output3$samples[[2]]
C3 = output3$samples[[3]]
fit_int_p3 = as.data.frame(rbind(C1, C2, C3))

C1 = output4$samples[[1]]
C2 = output4$samples[[2]]
C3 = output4$samples[[3]]
fit_int_p4 = as.data.frame(rbind(C1, C2, C3))

```

```{r}
col_code_p1 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VE", 
    colonne == 4 ~ "V5", 
    colonne == 5 ~ "AE1"
  )
  return(colonne)
}

col_code_p2 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "AE2"
  )
  return(colonne)
}

col_code_p3 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "AE2"
  )
  return(colonne)
}

col_code_p4 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "SZ", 
    colonne == 8 ~ "AE2"
  )
  return(colonne)
}
```



# Dispersion



```{r}

df_fid_1 = data.frame(natalfidelity = output1$mean$natalfidelity,
                 breedingfidelity = output1$mean$breedingfidelity,
                 mean_B = output1$mean$B %>% rowMeans(),
                 colony = c("LR", "MA", "VE", "V5", "AE1"),
                 Period = rep("1", 5)
) %>% 
  subset(., colony != "AE1")

df_fid_2 = data.frame(natalfidelity = output3$mean$natalfidelity,
                 breedingfidelity = output3$mean$breedingfidelity,
                 mean_B = output3$mean$B %>% rowMeans(),
                 colony = c("LR", "MA", "VS", "LA","SV", "WV", "AE2"),
                 Period = rep("2", 7)
)%>% 
  subset(., colony != "AE2")

df_fid_3 = data.frame(natalfidelity = output4$mean$natalfidelity,
                 breedingfidelity = output4$mean$breedingfidelity,
                 mean_B = output4$mean$B %>% rowMeans(),
                 colony = c("LR", "MA", "VS", "LA","SV", "WV", "SZ", "AE2"),
                 Period = rep("3", 8)
)%>% 
  subset(., colony != "AE2")

df_fid = rbind(df_fid_1,
               #df_fid_2,
               df_fid_3)

```



## Natal dispersion

```{r}
#natal fidelity
#P1
n.colony_p1 = 5
fit_int_p1_ = fit_int_p1 %>% 
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`, `natalfidelity[5]`) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%   # AJOUT KG
  mutate(colony_Period = case_when(
    param == "natalfidelity[1]" ~ "LR_p1", 
    param == "natalfidelity[2]" ~ "MA_p1", 
    param == "natalfidelity[3]" ~ "VE_p1", 
    param == "natalfidelity[4]" ~ "V5_p1", 
    param == "natalfidelity[5]" ~ "AE_p1"))

fit_int_p1_ = fit_int_p1_ %>% 
  subset(., colony_Period != "AE_p1")

colony_size_p1 = output1$mean$B %>% rowMeans()
colony_size_p1 = colony_size_p1[1:(n.colony_p1-1)]

fit_int_p1_ = fit_int_p1_ %>% 
  mutate(Period = rep("1987-2006", nrow(fit_int_p1_)))%>% 
  mutate(colony_size = rep(colony_size_p1, nrow(fit_int_p1_)/(n.colony_p1-1)))


#P3
n.colony_p3 = 7
fit_int_p3_ = fit_int_p3 %>% 
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`,
         `natalfidelity[5]`, `natalfidelity[6]`, `natalfidelity[7]`) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%   # AJOUT KG 
  mutate(colony_Period = case_when(
    param == "natalfidelity[1]" ~ "LR_p3", 
    param == "natalfidelity[2]" ~ "MA_p3", 
    param == "natalfidelity[3]" ~ "VS_p3", 
    param == "natalfidelity[4]" ~ "LA_p3", 
    param == "natalfidelity[5]" ~ "SV_p3", 
    param == "natalfidelity[6]" ~ "WV_p3", 
    param == "natalfidelity[7]" ~ "AE_p3"))

fit_int_p3_ = fit_int_p3_ %>% 
  subset(., colony_Period != "AE_p3")

colony_size_p3 = output3$mean$B %>% rowMeans()
colony_size_p3 = colony_size_p3[1:(n.colony_p3-1)]

fit_int_p3_ = fit_int_p3_ %>% 
  mutate(Period = rep("2007-2010", nrow(fit_int_p3_)))%>% 
  mutate(colony_size = rep(colony_size_p3, nrow(fit_int_p3_)/(n.colony_p3-1)))

#P4
n.colony_p4 = 8
fit_int_p4_ = fit_int_p4 %>% 
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`,
         `natalfidelity[5]`, `natalfidelity[6]`, `natalfidelity[7]`, `natalfidelity[8]`,) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%   # AJOUT KG 
  mutate(colony_Period = case_when(
    param == "natalfidelity[1]" ~ "LR_p4", 
    param == "natalfidelity[2]" ~ "MA_p4", 
    param == "natalfidelity[3]" ~ "VS_p4", 
    param == "natalfidelity[4]" ~ "LA_p4", 
    param == "natalfidelity[5]" ~ "SV_p4", 
    param == "natalfidelity[6]" ~ "WV_p4", 
    param == "natalfidelity[7]" ~ "SZ_p4", 
    param == "natalfidelity[8]" ~ "AE_p4"))

fit_int_p4_ = fit_int_p4_ %>% 
  subset(., colony_Period != "AE_p4")

colony_size_p4 = output4$mean$B %>% rowMeans()
colony_size_p4 = colony_size_p4[1:(n.colony_p4-1)]

fit_int_p4_ = fit_int_p4_ %>% 
  mutate(Period = rep("2010-2019", nrow(fit_int_p4_)))%>% 
  mutate(colony_size = rep(colony_size_p4, nrow(fit_int_p4_)/(n.colony_p4-1)))

natal_fidelity = rbind(fit_int_p1_,
                       #fit_int_p3_, 
                       fit_int_p4_)
```



```{r}
natal_fidelity_plot = ggplot() +
  stat_interval(data = natal_fidelity, aes(x = colony_size, y = value, color_ramp = after_stat(level), color = Period),
                .width = c(0.5, 0.95, 0.99),
                size = 1.5,
                alpha = 0.25) +
  geom_point(data = df_fid, aes(x = mean_B, y = natalfidelity)) +
  geom_text_repel(data = df_fid, aes(x = mean_B, y = natalfidelity, label = colony, color = Period), 
                  vjust = 0.25, hjust = 0.20, size = 3) + # Ajustez la taille des étiquettes si nécessaire
  coord_cartesian(ylim = c(0, 1)) +
  scale_x_continuous(trans = "log10") +
  scale_color_manual(values = c("1987-2006" = "darkblue", 
                                #"2007-2010" = "white", 
                                "2010-2019" = "darkorange")) + 
  ggthemes::theme_clean() +
  theme(
    legend.background = element_rect(color = "black", size = 0.5),
    panel.border = element_blank(), 
    legend.key = element_blank(),  
    legend.text = element_text(size = 6), 
    legend.title = element_text(size = 7, face = "bold"),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA),
    legend.position =  "none"
  ) +
  labs(color_ramp = "Confident (%)",
       title = "",
       x = "Mean Colony Size",
       y = "Natal fidelity")

#natal_fidelity_plot

```





## Breeding dispersion

```{r}
#natal fidelity
#P1
n.colony_p1 = 5
fit_int_p1_ = fit_int_p1 %>% 
  select(`breedingfidelity[1]`, `breedingfidelity[2]`, `breedingfidelity[3]`, `breedingfidelity[4]`, `breedingfidelity[5]`) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%    # AJOUT KG
  mutate(colony_Period = case_when(
    param == "breedingfidelity[1]" ~ "LR_p1", 
    param == "breedingfidelity[2]" ~ "MA_p1", 
    param == "breedingfidelity[3]" ~ "VE_p1", 
    param == "breedingfidelity[4]" ~ "V5_p1", 
    param == "breedingfidelity[5]" ~ "AE_p1"))

fit_int_p1_ = fit_int_p1_ %>% 
  subset(., colony_Period != "AE_p1")

colony_size_p1 = output1$mean$B %>% rowMeans()
colony_size_p1 = colony_size_p1[1:(n.colony_p1-1)]

fit_int_p1_ = fit_int_p1_ %>% 
  mutate(Period = rep("1987-2006", nrow(fit_int_p1_)))%>% 
  mutate(colony_size = rep(colony_size_p1, nrow(fit_int_p1_)/(n.colony_p1-1)))


#P3
n.colony_p3 = 7
fit_int_p3_ = fit_int_p3 %>% 
  select(`breedingfidelity[1]`, `breedingfidelity[2]`, `breedingfidelity[3]`, `breedingfidelity[4]`,
         `breedingfidelity[5]`, `breedingfidelity[6]`, `breedingfidelity[7]`) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%    # AJOUT KG
  mutate(colony_Period = case_when(
    param == "breedingfidelity[1]" ~ "LR_p3", 
    param == "breedingfidelity[2]" ~ "MA_p3", 
    param == "breedingfidelity[3]" ~ "VS_p3", 
    param == "breedingfidelity[4]" ~ "LA_p3", 
    param == "breedingfidelity[5]" ~ "SV_p3", 
    param == "breedingfidelity[6]" ~ "WV_p3", 
    param == "breedingfidelity[7]" ~ "AE_p3"))

fit_int_p3_ = fit_int_p3_ %>% 
  subset(., colony_Period != "AE_p3")

colony_size_p3 = output3$mean$B %>% rowMeans()
colony_size_p3 = colony_size_p3[1:(n.colony_p3-1)]

fit_int_p3_ = fit_int_p3_ %>% 
  mutate(Period = rep("2007-2010", nrow(fit_int_p3_)))%>% 
  mutate(colony_size = rep(colony_size_p3, nrow(fit_int_p3_)/(n.colony_p3-1)))

#P4
n.colony_p4 = 8
fit_int_p4_ = fit_int_p4 %>% 
  select(`breedingfidelity[1]`, `breedingfidelity[2]`, `breedingfidelity[3]`, `breedingfidelity[4]`,
         `breedingfidelity[5]`, `breedingfidelity[6]`, `breedingfidelity[7]`, `breedingfidelity[8]`,) %>% 
  rownames_to_column("iteration") %>%   # AJOUT KG
  pivot_longer(!iteration, names_to = "param", values_to = "value") %>%    # AJOUT KG
  mutate(colony_Period = case_when(
    param == "breedingfidelity[1]" ~ "LR_p4", 
    param == "breedingfidelity[2]" ~ "MA_p4", 
    param == "breedingfidelity[3]" ~ "VS_p4", 
    param == "breedingfidelity[4]" ~ "LA_p4", 
    param == "breedingfidelity[5]" ~ "SV_p4", 
    param == "breedingfidelity[6]" ~ "WV_p4", 
    param == "breedingfidelity[7]" ~ "SZ_p4", 
    param == "breedingfidelity[8]" ~ "AE_p4"))

fit_int_p4_ = fit_int_p4_ %>% 
  subset(., colony_Period != "AE_p4")

colony_size_p4 = output4$mean$B %>% rowMeans()
colony_size_p4 = colony_size_p4[1:(n.colony_p4-1)]

fit_int_p4_ = fit_int_p4_ %>% 
  mutate(Period = rep("2010-2019", nrow(fit_int_p4_)))%>% 
  mutate(colony_size = rep(colony_size_p4, nrow(fit_int_p4_)/(n.colony_p4-1)))

breeding_fidelity = rbind(fit_int_p1_,
                          #fit_int_p3_, 
                          fit_int_p4_)
```



```{r}
breeding_fidelity_plot = ggplot() +
  stat_interval(data = breeding_fidelity, aes(x = colony_size, y = value, color_ramp = after_stat(level), color = Period),
                .width = c(0.5, 0.95, 0.99),
                size = 1.5,
                alpha = 0.25) +
  geom_point(data = df_fid, aes(x = mean_B, y = breedingfidelity)) +
  geom_text_repel(data = df_fid, aes(x = mean_B, y = breedingfidelity, label = colony, color = Period), 
                  vjust = 0.25, hjust = 0.20, size = 3) + # Ajustez la taille des étiquettes si nécessaire
  coord_cartesian(ylim = c(0, 1)) +
  scale_x_continuous(trans = "log10") +
  scale_color_manual(values = c("1987-2006" = "darkblue", 
                                #"2007-2010" = "white", 
                                "2010-2019" = "darkorange")) + 
  ggthemes::theme_clean() +
  theme(
    legend.background = element_rect(color = "black", size = 0.5),
    panel.border = element_blank(), 
    legend.key = element_blank(),  
    legend.text = element_text(size = 6), 
    legend.title = element_text(size = 7, face = "bold"),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA),
    legend.position = "top"
  ) +
  labs(color_ramp = "Credible Interval (%)",
       title = "",
       x = "Mean Colony Size",
       y = "Breeding fidelity")

```

```{r, fig.width=6, fig.height=7}
fidelity_plot = breeding_fidelity_plot / natal_fidelity_plot
```

```{r, fig.width=6, fig.height=7}
fidelity_plot
```


```{r}
breeding_fidelity_p1 = fit_int_p1 %>% 
  select(`breedingfidelity[1]`,`breedingfidelity[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "1986-2006")

breeding_fidelity_p2 = fit_int_p2 %>% 
  select(`breedingfidelity[1]`,`breedingfidelity[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2006-2007")

breeding_fidelity_p2[breeding_fidelity_p2$param ==  "breedingfidelity[1]" ,c("value")] = 0


breeding_fidelity_p3 = fit_int_p3 %>% 
  select(`breedingfidelity[1]`,`breedingfidelity[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2007-2010")

breeding_fidelity_p4 = fit_int_p4 %>% 
  select(`breedingfidelity[1]`,`breedingfidelity[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2010-2019")

breeding_fidelity = rbind(breeding_fidelity_p1,
                   breeding_fidelity_p2,
                   breeding_fidelity_p3,
                   breeding_fidelity_p4)

```


```{r}
breeding_fidelity_plot_LR = breeding_fidelity %>%
  subset(., param == "breedingfidelity[1]") %>%
  ggplot(aes(x = factor(Period), y = value, group = param))  +
  stat_eye(
    adjust = 0.2,
    scale = 0.5) +
  labs(
    title = "",
    x = "Period",
    y = "Breeding Fidelity - LR",
    fill = "Cylinders"
  )+
   scale_y_continuous(breaks = c(0,0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
  ggthemes::theme_clean() +
  theme(
    panel.border = element_blank(), # Enlever la bordure du panel
    legend.key = element_blank(),  # Remove legend key background
    legend.background = element_blank(),  # Remove legend background
    axis.title = element_text(size = 11),  # Thicken axis titles
    axis.text = element_text(size = 10),  # Thicken axis text
    axis.line = element_line(size = 2),  # Thicken axis lines
    legend.text = element_text(size = 10),  # Thicken legend text
    legend.title = element_text(size = 12, face = "bold"),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA),
    axis.text.x = element_text(angle = 45, hjust = 1)  
  )
```


```{r}
breeding_fidelity_plot_MA = breeding_fidelity %>% 
  subset(., param == "breedingfidelity[2]") %>% 
  ggplot(aes(x = factor(Period), y = value, group = param))  +
  stat_eye(
    adjust = 0.2,
    scale = 0.5) +
  labs(
    title = "",
    x = "Period",
    y = "Breeding Fidelity - MA",
    fill = "Cylinders"
  )+
   scale_y_continuous(breaks = c(0,0.2, 0.4, 0.6,0.7), limits = c(0, 0.7)) +
  ggthemes::theme_clean() +
  theme(
    panel.border = element_blank(), # Enlever la bordure du panel
    legend.key = element_blank(),  # Remove legend key background
    legend.background = element_blank(),  # Remove legend background
    axis.title = element_text(size = 11),  # Thicken axis titles
    axis.text = element_text(size = 10),  # Thicken axis text
    axis.line = element_line(size = 2),  # Thicken axis lines
    legend.text = element_text(size = 10),  # Thicken legend text
    legend.title = element_text(size = 12, face = "bold"),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA),
    axis.text.x = element_text(angle = 45, hjust = 1)  
  )
```

```{r}
natal_fidelity_p1 = fit_int_p1 %>% 
  select(`natalfidelity[1]`,`natalfidelity[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "1986-2006")

natal_fidelity_p2 = fit_int_p2 %>% 
  select(`natalfidelity[1]`,`natalfidelity[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2006-2007")

natal_fidelity_p2[natal_fidelity_p2$param ==  "natalfidelity[1]" ,c("value")] = 0


natal_fidelity_p3 = fit_int_p3 %>% 
  select(`natalfidelity[1]`,`natalfidelity[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2007-2010")

natal_fidelity_p4 = fit_int_p4 %>% 
  select(`natalfidelity[1]`,`natalfidelity[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2010-2019")

natal_fidelity = rbind(natal_fidelity_p1,
                   natal_fidelity_p2,
                   natal_fidelity_p3,
                   natal_fidelity_p4)

```


```{r}
natal_fidelity_plot_LR = natal_fidelity %>%
  subset(., param == "natalfidelity[1]") %>%
  ggplot(aes(x = factor(Period), y = value, group = param))  +
  stat_eye(
    adjust = 0.2,
    scale = 0.5) +
  labs(
    title = "",
    x = "Period",
    y = "Natal Fidelity - LR",
    fill = "Cylinders"
  )+
   scale_y_continuous(breaks = c(0,0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
  ggthemes::theme_clean() +
  theme(
    panel.border = element_blank(), # Enlever la bordure du panel
    legend.key = element_blank(),  # Remove legend key background
    legend.background = element_blank(),  # Remove legend background
    axis.title = element_text(size = 11),  # Thicken axis titles
    axis.text = element_text(size = 10),  # Thicken axis text
    axis.line = element_line(size = 2),  # Thicken axis lines
    legend.text = element_text(size = 10),  # Thicken legend text
    legend.title = element_text(size = 12, face = "bold"),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA),
    axis.text.x = element_text(angle = 45, hjust = 1) 
  )
```


```{r}
natal_fidelity_plot_MA = natal_fidelity %>% 
  subset(., param == "natalfidelity[2]") %>% 
  ggplot(aes(x = factor(Period), y = value, group = param))  +
  stat_eye(
    adjust = 0.2,
    scale = 0.5) +
  labs(
    title = "",
    x = "Period",
    y = "Natal Fidelity - MA",
    fill = "Cylinders"
  )+
   scale_y_continuous(breaks = c(0,0.2, 0.4, 0.6,0.7), limits = c(0, 0.7)) +
  ggthemes::theme_clean() +
  theme(
    panel.border = element_blank(), # Enlever la bordure du panel
    legend.key = element_blank(),  # Remove legend key background
    legend.background = element_blank(),  # Remove legend background
    axis.title = element_text(size = 11),  # Thicken axis titles
    axis.text = element_text(size = 10),  # Thicken axis text
    axis.line = element_line(size = 2),  # Thicken axis lines
    legend.text = element_text(size = 10),  # Thicken legend text
    legend.title = element_text(size = 12, face = "bold"),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA),
    axis.text.x = element_text(angle = 45, hjust = 1) 
  )
```


```{r}
plot_LR_MA = (breeding_fidelity_plot_LR + breeding_fidelity_plot_MA)/
(natal_fidelity_plot_LR + natal_fidelity_plot_MA)
```


```{r}
plot_LR_MA
```














