---
title: ""
author: "Odin Rumianowski"
date: "2024"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache = FALSE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(MCMCvis)
library(knitr)
library(patchwork)
library(hrbrthemes)
library(scales)
library(tidyquant)
library(ggthemes)
library(ggdist)
library(ggrepel)
```

```{r}
load(file = "data/period_1234/out1_p1_v15_5_p1_4.Rda")
output1= out1
load(file = "data/period_1234/out1_p1_v15_5_p2_4.Rda")
output2= out1
load(file = "data/period_1234/out1_p1_v15_5_p3_4.Rda")
output3= out1
load(file = "data/period_1234/out1_p1_v15_5_p4_4.Rda")
output4= out1
```

```{r}
load(file = "data/period_1234/B_p1_4_2805.Rda")

survey_p1 = B %>%
  as.data.frame() 

survey_p1 = rbind(survey_p1, colSums(survey_p1)) %>%
  mutate(colony = c("LR", "MA", "VE", "V5", "AE1", "Population")) %>% 
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer())


load(file = "data/period_1234/B_p3_4_2805.Rda")

survey_p3 = B %>%
  as.data.frame() 
  
survey_p3 = rbind(survey_p3, colSums(survey_p3)) %>% 
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "AE2", "Population")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) %>% 
  subset(year != 2010)


load(file = "data/period_1234/B_p4_4_2805.Rda")

survey_p4 = B %>%
  as.data.frame()
  
survey_p4 = rbind(survey_p4, colSums(survey_p4)) %>% 
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "SZ", "AE2", "Population")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) 


survey = rbind(survey_p1,
               survey_p3,
               survey_p4)

```

```{r}
C1 = output1$samples[[1]]
C2 = output1$samples[[2]]
C3 = output1$samples[[3]]
fit_int_p1 = as.data.frame(rbind(C1, C2, C3))

C1 = output2$samples[[1]]
C2 = output2$samples[[2]]
C3 = output2$samples[[3]]
fit_int_p2 = as.data.frame(rbind(C1, C2, C3))

C1 = output3$samples[[1]]
C2 = output3$samples[[2]]
C3 = output3$samples[[3]]
fit_int_p3 = as.data.frame(rbind(C1, C2, C3))

C1 = output4$samples[[1]]
C2 = output4$samples[[2]]
C3 = output4$samples[[3]]
fit_int_p4 = as.data.frame(rbind(C1, C2, C3))

```


```{r}
col_code_p1 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VE", 
    colonne == 4 ~ "V5", 
    colonne == 5 ~ "AE1"
  )
  return(colonne)
}

col_code_p2 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "AE2"
  )
  return(colonne)
}

col_code_p3 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "AE2"
  )
  return(colonne)
}

col_code_p4 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "SZ", 
    colonne == 8 ~ "AE2"
  )
  return(colonne)
}
```


## Breeders


```{r}
B_p1 <- c()

for (colony in 1:5) {
  for (year in 1:21) {
    combinaison <- paste0("B[", colony, ",", year, "]")
    B_p1 <- c(B_p1, combinaison)
  }
}
```

```{r}
B_distribution_p1 = fit_int_p1 %>%
  select(B_p1) %>%
  rownames_to_column("iteration") %>%
  pivot_longer(!iteration, names_to = "colonne_annee", values_to = "value") %>%
  separate(colonne_annee, into = c("colony", "annee"), sep = ",") %>% 
  mutate(colony = substr(colony, 3, nchar(colony)) %>% as.factor())%>% 
  mutate(annee = substr(annee, 1, nchar(annee) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p2(colony)) %>% 
  group_by(annee, iteration) %>% 
  mutate(Population = sum(value)) %>% 
  ungroup() %>% 
  select(Population, annee)%>% 
  group_by(annee) %>%
  summarise(med = median(Population),
            i95.inf = quantile(Population, probs = 0.025),
            i95.sup = quantile(Population, probs = 0.975)) %>% 
  mutate(year = annee + 1985)
```


```{r}
B_p3 <- c()

for (colony in 1:7) {
  for (year in 1:3) {
    combinaison <- paste0("B[", colony, ",", year, "]")
    B_p3 <- c(B_p3, combinaison)
  }
}
```


```{r}
B_distribution_p3 = fit_int_p3 %>%
  select(B_p3) %>%
  rownames_to_column("iteration") %>%
  pivot_longer(!iteration, names_to = "colonne_annee", values_to = "value") %>%
  separate(colonne_annee, into = c("colony", "annee"), sep = ",") %>% 
  mutate(colony = substr(colony, 3, nchar(colony)) %>% as.factor())%>% 
  mutate(annee = substr(annee, 1, nchar(annee) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p2(colony)) %>% 
  group_by(annee, iteration) %>% 
  mutate(Population = sum(value)) %>% 
  ungroup() %>% 
  select(Population, annee)%>% 
  group_by(annee) %>%
  summarise(med = median(Population),
            i95.inf = quantile(Population, probs = 0.025),
            i95.sup = quantile(Population, probs = 0.975)) %>% 
  mutate(year = annee + 2006)
```

```{r}
B_p4 <- c()

for (colony in 1:8) {
  for (year in 1:10) {
    combinaison <- paste0("B[", colony, ",", year, "]")
    B_p4 <- c(B_p4, combinaison)
  }
}
```


```{r}
B_distribution_p4 = fit_int_p4 %>%
  select(B_p4) %>%
  rownames_to_column("iteration") %>%
  pivot_longer(!iteration, names_to = "colonne_annee", values_to = "value") %>%
  separate(colonne_annee, into = c("colony", "annee"), sep = ",") %>% 
  mutate(colony = substr(colony, 3, nchar(colony)) %>% as.factor())%>% 
  mutate(annee = substr(annee, 1, nchar(annee) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p2(colony)) %>% 
  group_by(annee, iteration) %>% 
  mutate(Population = sum(value)) %>% 
  ungroup() %>% 
  select(Population, annee)%>% 
  group_by(annee) %>%
  summarise(med = median(Population),
            i95.inf = quantile(Population, probs = 0.025),
            i95.sup = quantile(Population, probs = 0.975)) %>% 
  mutate(year = annee + 2009)
```


```{r}
Population_distribution = rbind(B_distribution_p1, B_distribution_p3, B_distribution_p4)
```


```{r}
Population_2006 = Population_distribution %>% subset(., year == 2006) %>% 
  select(med)


Population_2007 = Population_distribution %>% subset(., year == 2007)%>% 
  select(med)

(Population_2006-Population_2007)

(Population_2006-Population_2007)/Population_2007
```


```{r}

 y_breaks <- 0:11*1000
 population_plot =Population_distribution %>%  
    ggplot() +
    geom_ribbon(data = Population_distribution ,aes(x = year, ymin=i95.inf,ymax=i95.sup), alpha = 0.3)+
    geom_line(data = Population_distribution, aes(x = year, y = med), size = 1.1 , show.legend = F)+
    geom_point(data = survey %>% subset(., colony == "Population"), aes(x = year, y = value), shape = 4, size = 2 )+
    scale_linewidth_manual(values = c(1.5)) +
    geom_vline(xintercept = 2006.5, color = "bisque3", alpha = 0.5, size=6)+
    coord_cartesian(ylim = c(0, max(y_breaks))) +
    labs(x = "", y = "",
         title = " ",
         subtitle = "Population",
         colour = "", linewidth = "", alpha = "") +
    theme_classic() +
    theme(legend.text = element_text(size = 10),
          plot.subtitle = element_text(margin = margin(t = 0, b = -10), hjust = 0.02))
  
population_plot


```


# Colonies

## Breeders


```{r}
B_p1 <- c()

for (colony in 1:5) {
  for (year in 1:21) {
    combinaison <- paste0("B[", colony, ",", year, "]")
    B_p1 <- c(B_p1, combinaison)
  }
}

B_distribution_p1 = fit_int_p1 %>%
  select(B_p1) %>%
  pivot_longer(cols = everything(), names_to = "colonne_annee", values_to = "value") %>%
  separate(colonne_annee, into = c("colony", "annee"), sep = ",") %>% 
  mutate(colony = substr(colony, 3, nchar(colony)) %>% as.factor())%>% 
  mutate(annee = substr(annee, 1, nchar(annee) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p1(colony)) %>% 
  group_by(annee, colony) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(year = annee + 1985)
```


```{r}
B_p3 <- c()

for (colony in 1:7) {
  for (year in 1:3) {
    combinaison <- paste0("B[", colony, ",", year, "]")
    B_p3 <- c(B_p3, combinaison)
  }
}

B_distribution_p3 = fit_int_p3 %>%
  select(B_p3) %>%
  pivot_longer(cols = everything(), names_to = "colonne_annee", values_to = "value") %>%
  separate(colonne_annee, into = c("colony", "annee"), sep = ",") %>% 
  mutate(colony = substr(colony, 3, nchar(colony)) %>% as.factor())%>% 
  mutate(annee = substr(annee, 1, nchar(annee) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p3(colony)) %>% 
  group_by(annee, colony) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(year = annee + 2006)
```

```{r}
B_p4 <- c()

for (colony in 1:8) {
  for (year in 1:10) {
    combinaison <- paste0("B[", colony, ",", year, "]")
    B_p4 <- c(B_p4, combinaison)
  }
}

B_distribution_p4 = fit_int_p4 %>%
  select(B_p4) %>%
  pivot_longer(cols = everything(), names_to = "colonne_annee", values_to = "value") %>%
  separate(colonne_annee, into = c("colony", "annee"), sep = ",") %>% 
  mutate(colony = substr(colony, 3, nchar(colony)) %>% as.factor())%>% 
  mutate(annee = substr(annee, 1, nchar(annee) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p4(colony)) %>% 
  group_by(annee, colony) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(year = annee + 2009)
```


```{r}
B_distribution = rbind(B_distribution_p1,
                       B_distribution_p3,
                       B_distribution_p4)
```

```{r}
plot.colonies_panel <- function(etang){
  if(etang == "LR" | etang == "AE1"){
    y_breaks <- 0:7*1000
  }else{
    y_breaks <- 0:6*300
  }
 panel.grandes_colonies <- B_distribution |> 
    mutate(focus = ifelse(colony == etang, etang, "Autres"),
           focus = factor(focus, levels = c(etang, "Autres")),
           annee_observation_colonie = year %>% as.character() %>% as.integer()) %>% 
    ggplot() +
    geom_line( aes(x = year, y = med, 
                  group = colony, colour = focus, linewidth = focus,
                  alpha = focus),
              show.legend = F) +
    scale_colour_manual(values = c("navyblue", "black")) +
    geom_ribbon(data = B_distribution %>% subset(., colony == etang),aes(x = year, ymin=i95.inf,ymax=i95.sup), alpha = 0.3)+
    geom_point(data = survey %>% subset(., colony == etang), aes(x = year, y = value), shape = 4, size = 2 )+
    scale_linewidth_manual(values = c(1.1, 1)) +
    scale_alpha_manual(values = c(1, 0.2)) +
    geom_vline(xintercept = 2006.5, color = "bisque3", alpha = 0.5, size=6) +
    coord_cartesian(ylim = c(0, max(y_breaks))) +
    labs(x = "", y = "",
         title = " ",
         subtitle = etang,
         colour = "", linewidth = "", alpha = "") +
    theme_classic() +
    theme(legend.text = element_text(size = 10),
          plot.subtitle = element_text(margin = margin(t = 0, b = -10), hjust = 0.02))
  
  return(panel.grandes_colonies)
}


```



```{r, fig.width=5, fig.height=15}
plot_number =
  (
    population_plot /
        plot.colonies_panel("LR") /
        plot.colonies_panel("MA") / plot.colonies_panel("VE") 
)|(
  (plot.colonies_panel("V5")+plot.colonies_panel("VS")) /
  (plot.colonies_panel("LA")+plot.colonies_panel("SV")) / 
  (plot.colonies_panel("WV")+plot.colonies_panel("SZ"))/
  (plot.colonies_panel("AE1")+plot.colonies_panel("AE2"))
)
```


```{r, fig.width=5, fig.height=15}
plot_number
```


```{r, fig.width=5, fig.height=15}
# ggsave(plot_number, filename = "plot_number.png",
#        dpi = 600, width = 23, height = 21, units = "cm")
```

