---
title: ""
author: "Odin Rumianowski"
date: "2024"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache = FALSE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(MCMCvis)
library(knitr)
library(patchwork)
library(hrbrthemes)
library(scales)
library(tidyquant)
library(ggthemes)
library(ggdist)
library(ggrepel)
```



```{r}
load(file = "data/period_1234/out1_p1_v15_5_p1_4.Rda")
output1= out1
load(file = "data/period_1234/out1_p1_v15_5_p2_4.Rda")
output2= out1
load(file = "data/period_1234/out1_p1_v15_5_p3_4.Rda")
output3= out1
load(file = "data/period_1234/out1_p1_v15_5_p4_4.Rda")
output4= out1
```

```{r}
load(file = "data/period_1234/B_p1_4_2805.Rda")

survey_p1 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VE", "V5", "AE1")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer())


load(file = "data/period_1234/B_p3_4_2805.Rda")

survey_p3 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "AE3")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) 

load(file = "data/period_1234/B_p4_4_2805.Rda")

survey_p4 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "SZ", "AE4")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) %>% 
  subset(year != 2010)

survey = rbind(survey_p1,
               survey_p3,
               survey_p4)

```


```{r}
C1 = output1$samples[[1]]
C2 = output1$samples[[2]]
C3 = output1$samples[[3]]
fit_int_p1 = as.data.frame(rbind(C1, C2, C3))

C1 = output2$samples[[1]]
C2 = output2$samples[[2]]
C3 = output2$samples[[3]]
fit_int_p2 = as.data.frame(rbind(C1, C2, C3))

C1 = output3$samples[[1]]
C2 = output3$samples[[2]]
C3 = output3$samples[[3]]
fit_int_p3 = as.data.frame(rbind(C1, C2, C3))

C1 = output4$samples[[1]]
C2 = output4$samples[[2]]
C3 = output4$samples[[3]]
fit_int_p4 = as.data.frame(rbind(C1, C2, C3))

```

```{r}

# Period 1
survie <- c()

for (age in 1:2) {
  for (year in 1:20) {
    combinaison <- paste0("phi[", age, ",", year, "]")
    survie <- c(survie, combinaison)
  }
}

survie_p1 = fit_int_p1 %>%
  select(survie) %>%
  pivot_longer(cols = everything(), names_to = "age_annee", values_to = "value") %>%
  separate(age_annee, into = c("age", "annee"), sep = ",") %>% 
  mutate(age = substr(age, 5, nchar(age)) %>% as.factor()) %>% 
  mutate(annee = substr(annee, 1, nchar(annee) - 1) %>% as.integer()) %>% 
  group_by(annee, age) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(year = annee + 1986)
```


```{r}
# Period 2
survie <- c()
for (age in 1:2) {
    combinaison <- paste0("phi[", age,"]")
    survie <- c(survie, combinaison)
}

survie_p2 = fit_int_p2 %>%
  select(survie) %>%
  pivot_longer(cols = everything(), names_to = "age", values_to = "value") %>%
  mutate(age = substr(age, 5, nchar(age)-1) %>% as.factor()) %>% 
  mutate(annee = 1) %>% 
  group_by(age, annee) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(year = annee + 2006)
```


```{r}
# Period 3
survie <- c()
for (age in 1:2) {
  for (year in 1:3) {
    combinaison <- paste0("phi[", age, ",", year, "]")
    survie <- c(survie, combinaison)
  }
}

survie_p3 = fit_int_p3 %>%
  select(survie) %>%
  pivot_longer(cols = everything(), names_to = "age_annee", values_to = "value") %>%
  separate(age_annee, into = c("age", "annee"), sep = ",") %>% 
  mutate(age = substr(age, 5, nchar(age)) %>% as.factor()) %>% 
  mutate(annee = substr(annee, 1, nchar(annee) - 1) %>% as.integer()) %>% 
  group_by(annee, age) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(year = annee + 2007)
```

```{r}
# Period 4
survie <- c()
for (age in 1:2) {
  for (year in 1:10) {
    combinaison <- paste0("phi[", age, ",", year, "]")
    survie <- c(survie, combinaison)
  }
}

survie_p4 = fit_int_p4 %>%
  select(survie) %>%
  pivot_longer(cols = everything(), names_to = "age_annee", values_to = "value") %>%
  separate(age_annee, into = c("age", "annee"), sep = ",") %>% 
  mutate(age = substr(age, 5, nchar(age)) %>% as.factor()) %>% 
  mutate(annee = substr(annee, 1, nchar(annee) - 1) %>% as.integer()) %>% 
  group_by(annee, age) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(year = annee + 2010)
```


```{r}
survie_distribution = rbind(survie_p1,
                            survie_p2,
                            survie_p3,
                            survie_p4)

```


```{r}
age_labels <- c("1" = "Juvenile", "2" = "Adult")

economist_colors <- ggthemes::economist_pal()(2)

plot_survival <- ggplot() +
  geom_point(data = survie_distribution, aes(x = year, y = med, color = factor(age)), position = position_dodge(width = 0.5)) +
  geom_line(data = survie_distribution, aes(x = year, y = med, color = factor(age)), position = position_dodge(width = 0.5)) +
  geom_linerange(data = survie_distribution, aes(x = year, ymin = i95.inf, ymax = i95.sup, color = factor(age)), 
                 position = position_dodge(width = 0.5), show.legend = FALSE, alpha = 0.8) +
  labs(x = "         Year", y = "Survival", title = "", subtitle = "", color = "Age class") +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
  scale_color_manual(values = economist_colors, labels = age_labels) +
  ggthemes::theme_clean() +
  geom_vline(xintercept = 2006.5, color = "bisque3", alpha = 0.5, size=3) +
  guides(alpha = guide_legend(override.aes = list(alpha = 1)))+
  theme(
    legend.key = element_blank(),  
    legend.background = element_blank(),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA),  
    legend.position = "top"
  )+
  geom_text(aes(x = 1986.5, y = 0.99, label = "C"), 
            hjust = 0, vjust = 0.5, size = 7.5, fontface = "bold")
```


```{r}
print(plot_survival)

```


Graphe des moyennes de survie

```{r}
# Adultes
survie_ad_p1 = fit_int_p1 %>% 
  select(`mean_phi[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "1986-2006")

survie_ad_p2 = fit_int_p2 %>% 
  select(`phi[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2006-2007")

survie_ad_p3 = fit_int_p3 %>% 
  select(`mean_phi[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2007-2010")

survie_ad_p4 = fit_int_p4 %>% 
  select(`mean_phi[2]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2010-2019")

survie_ad = rbind(survie_ad_p1,
                  survie_ad_p2,
                  survie_ad_p3,
                  survie_ad_p4)

```

```{r}
# Juveniles

survie_juv_p1 = fit_int_p1 %>% 
  select(`mean_phi[1]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "1986-2006")

survie_juv_p2 = fit_int_p2 %>% 
  select(`phi[1]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2006-2007")

survie_juv_p3 = fit_int_p3 %>% 
  select(`mean_phi[1]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2007-2010")

survie_juv_p4 = fit_int_p4 %>% 
  select(`mean_phi[1]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(Period = "2010-2019")

survie_juv = rbind(survie_juv_p1,
                   survie_juv_p2,
                   survie_juv_p3,
                   survie_juv_p4)

```




```{r}
survie_ad_plot = survie_ad %>% 
  ggplot(aes(x = factor(Period), y = value))  +
  geom_vline(xintercept = 2, color = "bisque3", alpha = 0.5, size=28)  +
  stat_eye(
    adjust = 0.2,
    scale = 0.5) +
  labs(
    title = "",
    x = "Period",
    y = "Adult Survival",
    fill = "Cylinders"
  )+
  scale_y_continuous(breaks = c(0,0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
  ggthemes::theme_clean() +
  theme(
    panel.border = element_blank(), 
    legend.key = element_blank(),  
    legend.background = element_blank(),  
    axis.title = element_text(size = 11),  
    axis.text = element_text(size = 10),  
    axis.line = element_line(size = 2),  
    legend.text = element_text(size = 10),  
    legend.title = element_text(size = 12, face = "bold"),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA), 
  )+
  geom_text(aes(x = 0.6, y = 0.975, label = "A"), 
            hjust = 0, vjust = 0.5, size = 7.5, fontface = "bold")
#survie_ad_plot

```

```{r}
survie_juv_plot = survie_juv %>% 
  ggplot(aes(x = factor(Period), y = value))+
  geom_vline(xintercept = 2, color = "bisque3", alpha = 0.5, size=28)  +
  stat_eye(
    adjust = 0.2,
    scale = 0.5) +
  labs(
    title = "",
    x = "Period",
    y = "Juvenile Survival",
    fill = "Cylinders"
  )+
   scale_y_continuous(breaks = c(0,0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
  ggthemes::theme_clean() +
  theme(
    panel.border = element_blank(), 
    legend.key = element_blank(),  
    legend.background = element_blank(),  
    axis.title = element_text(size = 11),  
    axis.text = element_text(size = 10), 
    axis.line = element_line(size = 2),  
    legend.text = element_text(size = 10),  
    legend.title = element_text(size = 12, face = "bold"),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA), 
  ) +
  geom_text(aes(x = 0.6, y = 0.975, label = "B"), 
            hjust = 0, vjust = 0.5, size = 7.5, fontface = "bold")

# survie_juv_plot
```



```{r, fig.width=8, fig.height=8}
survie_plot = (survie_ad_plot +  survie_juv_plot) / plot_survival 
survie_plot

# ggsave(survie_plot, filename = "survie_plot.png",
#        dpi = 600, width = 18, height = 18, units = "cm")
```
