---
title: ""
author: "Odin Rumianowski"
date: "2024"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache = FALSE)
```
```{r}
library(tidyverse)
library(ggplot2)
library(MCMCvis)
library(knitr)
library(patchwork)
library(hrbrthemes)
library(scales)
library(tidyquant)
library(ggthemes)
library(ggdist)
library(ggrepel)
```



```{r}
load(file = "data/period_1234/out1_p1_v15_5_p1_4.Rda")
output1= out1
load(file = "data/period_1234/out1_p1_v15_5_p2_4.Rda")
output2= out1
load(file = "data/period_1234/out1_p1_v15_5_p3_4.Rda")
output3= out1
load(file = "data/period_1234/out1_p1_v15_5_p4_4.Rda")
output4= out1
```

```{r}
load(file = "data/period_1234/B_p1_4_2805.Rda")

survey_p1 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VE", "V5", "AE1")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer())


load(file = "data/period_1234/B_p3_4_2805.Rda")

survey_p3 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "AE3")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) 

load(file = "data/period_1234/B_p4_4_2805.Rda")

survey_p4 = B %>%
  as.data.frame() %>%
  mutate(colony = c("LR", "MA", "VS", "LA","SV", "WV", "SZ", "AE4")) %>%
  gather(year, value, -colony)%>% 
  mutate(year = year %>% as.character() %>% as.integer()) %>% 
  subset(year != 2010)

survey = rbind(survey_p1,
               survey_p3,
               survey_p4)

```


```{r}
C1 = output1$samples[[1]]
C2 = output1$samples[[2]]
C3 = output1$samples[[3]]
fit_int_p1 = as.data.frame(rbind(C1, C2, C3))

C1 = output2$samples[[1]]
C2 = output2$samples[[2]]
C3 = output2$samples[[3]]
fit_int_p2 = as.data.frame(rbind(C1, C2, C3))

C1 = output3$samples[[1]]
C2 = output3$samples[[2]]
C3 = output3$samples[[3]]
fit_int_p3 = as.data.frame(rbind(C1, C2, C3))

C1 = output4$samples[[1]]
C2 = output4$samples[[2]]
C3 = output4$samples[[3]]
fit_int_p4 = as.data.frame(rbind(C1, C2, C3))

```


# Dispersion

```{r}
col_code_p1 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VE", 
    colonne == 4 ~ "V5", 
    colonne == 5 ~ "AE1"
  )
  return(colonne)
}

col_code_p2 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "AE2"
  )
  return(colonne)
}

col_code_p3 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "AE2"
  )
  return(colonne)
}

col_code_p4 <- function(colonne) {
  colonne <- case_when(
    colonne == 1 ~ "LR", 
    colonne == 2 ~ "MA", 
    colonne == 3 ~ "VS", 
    colonne == 4 ~ "LA", 
    colonne == 5 ~ "SV", 
    colonne == 6 ~ "WV", 
    colonne == 7 ~ "SZ", 
    colonne == 8 ~ "AE2"
  )
  return(colonne)
}
```



```{r}

df_fid_1 = data.frame(natalfidelity = output1$mean$natalfidelity,
                 breedingfidelity = output1$mean$breedingfidelity,
                 mean_B = output1$mean$B %>% rowMeans(),
                 colony = c("LR", "MA", "VE", "V5", "AE1"),
                 Period = rep("1", 5)
) %>% 
  subset(., colony != "AE1")

df_fid_2 = data.frame(natalfidelity = output3$mean$natalfidelity,
                 breedingfidelity = output3$mean$breedingfidelity,
                 mean_B = output3$mean$B %>% rowMeans(),
                 colony = c("LR", "MA", "VS", "LA","SV", "WV", "AE2"),
                 Period = rep("2", 7)
)%>% 
  subset(., colony != "AE2")

df_fid_3 = data.frame(natalfidelity = output4$mean$natalfidelity,
                 breedingfidelity = output4$mean$breedingfidelity,
                 mean_B = output4$mean$B %>% rowMeans(),
                 colony = c("LR", "MA", "VS", "LA","SV", "WV", "SZ", "AE2"),
                 Period = rep("3", 8)
)%>% 
  subset(., colony != "AE2")

df_fid = rbind(df_fid_1,
               #df_fid_2,
               df_fid_3)

```




## Natal dispersion

```{r}
#natal fidelity
#P1
n.colony_p1 = 5
fit_int_p1_ = fit_int_p1 %>% 
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`, `natalfidelity[5]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(colony_Period = case_when(
    param == "natalfidelity[1]" ~ "LR_p1", 
    param == "natalfidelity[2]" ~ "MA_p1", 
    param == "natalfidelity[3]" ~ "VE_p1", 
    param == "natalfidelity[4]" ~ "V5_p1", 
    param == "natalfidelity[5]" ~ "AE_p1"))

fit_int_p1_ = fit_int_p1_ %>% 
  subset(., colony_Period != "AE_p1")

colony_size_p1 = output1$mean$B %>% rowMeans()
colony_size_p1 = colony_size_p1[1:(n.colony_p1-1)]

fit_int_p1_ = fit_int_p1_ %>% 
  mutate(Period = rep("1987-2006", nrow(fit_int_p1_)))%>% 
  mutate(colony_size = rep(colony_size_p1, nrow(fit_int_p1_)/(n.colony_p1-1)))


#P2
n.colony_p4 = 8
fit_int_p4_ = fit_int_p4 %>% 
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`,
         `natalfidelity[5]`, `natalfidelity[6]`, `natalfidelity[7]`, `natalfidelity[8]`) %>% 
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>% 
  mutate(colony_Period = case_when(
    param == "natalfidelity[1]" ~ "LR_p2", 
    param == "natalfidelity[2]" ~ "MA_p2", 
    param == "natalfidelity[3]" ~ "VS_p2", 
    param == "natalfidelity[4]" ~ "LA_p2", 
    param == "natalfidelity[5]" ~ "SV_p2", 
    param == "natalfidelity[6]" ~ "WV_p2", 
    param == "natalfidelity[7]" ~ "SZ_p2", 
    param == "natalfidelity[8]" ~ "AE_p2"))

fit_int_p4_ = fit_int_p4_ %>% 
  subset(., colony_Period != "AE_p2")

colony_size_p4 = output4$mean$B %>% rowMeans()
colony_size_p4 = colony_size_p4[1:(n.colony_p4-1)]

fit_int_p4_ = fit_int_p4_ %>% 
  mutate(Period = rep("2007-2019", nrow(fit_int_p4_)))%>% 
  mutate(colony_size = rep(colony_size_p4, nrow(fit_int_p4_)/(n.colony_p4-1)))

natal_fidelity = rbind(fit_int_p1_, fit_int_p4_)
```

```{r}

natalfidelity_p1 = fit_int_p1 %>%
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`,
         `natalfidelity[5]`) %>%
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>%
  mutate(colony = substr(param, 15, nchar(param) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p1(colony)) %>% 
  group_by(colony) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(Period = "1987-2006")%>% 
  rename(natal_med = med,
         natal_i95.inf = i95.inf,
         natal_i95.sup = i95.sup)

breedingfidelity_p1 = fit_int_p1 %>%
  select(`breedingfidelity[1]`, `breedingfidelity[2]`, `breedingfidelity[3]`, `breedingfidelity[4]`,
         `breedingfidelity[5]`) %>%
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>%
  mutate(colony = substr(param, 18, nchar(param) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p1(colony)) %>% 
  group_by(colony) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(Period = "1987-2006") %>% 
  rename(breeding_med = med,
         breeding_i95.inf = i95.inf,
         breeding_i95.sup = i95.sup)



natalfidelity_p4 = fit_int_p4 %>%
  select(`natalfidelity[1]`, `natalfidelity[2]`, `natalfidelity[3]`, `natalfidelity[4]`,
         `natalfidelity[5]`, `natalfidelity[6]`, `natalfidelity[7]`, `natalfidelity[8]`) %>%
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>%
  mutate(colony = substr(param, 15, nchar(param) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p4(colony)) %>% 
  group_by(colony) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(Period = "2011-2019")%>% 
  rename(natal_med = med,
         natal_i95.inf = i95.inf,
         natal_i95.sup = i95.sup)

breedingfidelity_p4 = fit_int_p4 %>%
  select(`breedingfidelity[1]`, `breedingfidelity[2]`, `breedingfidelity[3]`, `breedingfidelity[4]`,
         `breedingfidelity[5]`, `breedingfidelity[6]`, `breedingfidelity[7]`, `breedingfidelity[8]`) %>%
  pivot_longer(cols = everything(), names_to = "param", values_to = "value") %>%
  mutate(colony = substr(param, 18, nchar(param) - 1) %>% as.integer()) %>% 
  mutate(colony = col_code_p2(colony)) %>% 
  group_by(colony) %>%
  summarise(med = median(value),
            i95.inf = quantile(value, probs = 0.025),
            i95.sup = quantile(value, probs = 0.975)) %>% 
  mutate(Period = "2011-2019") %>% 
  rename(breeding_med = med,
         breeding_i95.inf = i95.inf,
         breeding_i95.sup = i95.sup)

fidelity_p1 = merge (natalfidelity_p1, breedingfidelity_p1, by=c("colony", "Period"))
fidelity_p4 = merge (natalfidelity_p4, breedingfidelity_p4, by=c("colony", "Period"))

fidelity = rbind(fidelity_p1,
                 fidelity_p4) %>% 
  subset(., !(colony %in% c("AE1", "AE2")))


```




```{r, fig.width=6, fig.height=5}
plot_natal_breeding_fid = ggplot()+
  geom_text_repel(data = fidelity, aes(x = natal_med, y = breeding_med, label = colony, color = Period),
                  vjust = 0.25, hjust = 0.20, size = 4)+
  geom_linerange(data = fidelity, aes(x = natal_med, ymin = breeding_i95.inf, ymax = breeding_i95.sup, color = Period), 
                 position = position_dodge(width = 0.5), show.legend = FALSE, size = 1.5, alpha = 0.4) +
  scale_color_manual(values = c("1987-2006" = "darkblue", "2011-2019" = "darkorange"))+
  geom_linerange(data = fidelity, aes(y = breeding_med, xmin = natal_i95.inf, xmax = natal_i95.sup, color = Period), 
                 position = position_dodge(width = 0.5), show.legend = FALSE, size = 1.5, alpha = 0.4) +
  geom_point(data = fidelity, aes(x = natal_med, y = breeding_med)  )   +
  scale_y_continuous(breaks = c(0,0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1))  +
  scale_x_continuous(breaks = c(0,0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1))+
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  ggthemes::theme_clean() +
  theme(legend.position = c(0.8, 0.2),
    legend.background = element_rect(color = "black", size = 0.5),
    panel.border = element_blank(), # Enlever la bordure du panel
    legend.key = element_blank(),  # Remove legend key background
    legend.text = element_text(size = 8),  # Thicken legend text
    legend.title = element_text(size = 10, face = "bold"),  # Thicken legend title
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA)
  )+
  labs(color = "Credible interval - 95%",
       title = "",
       label = "Colony",
    x = "Natal fidelity",
    y = "Breeding fidelity")
```


```{r, fig.width=6, fig.height=5}
plot_natal_breeding_fid
```


```{r, fig.width=6, fig.height=5}
# ggsave(plot_natal_breeding_fid, filename = "plot_natal_breeding_fid.png",
#        dpi = 600, width = 18, height = 18, units = "cm")
```


