---
title: ""
author: "Odin Rumianowski"
date: "2024"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
---

 
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache = FALSE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(MCMCvis)
library(knitr)
library(patchwork)
library(hrbrthemes)
library(scales)
library(tidyquant)
library(ggthemes)
library(ggdist)
library(ggrepel)
library(patchwork)
```



```{r}

load(file = "data/period_1234/out1_p1_v15_5_p1_4.Rda")
output1= out1
load(file = "data/period_1234/out1_p1_v15_5_p2_4.Rda")
output2= out1
load(file = "data/period_1234/out1_p1_v15_5_p3_4.Rda")
output3= out1
load(file = "data/period_1234/out1_p1_v15_5_p4_4.Rda")
output4= out1
```

```{r}
C1 = output1$samples[[1]]
C2 = output1$samples[[2]]
C3 = output1$samples[[3]]
fit_int_p1 = as.data.frame(rbind(C1, C2, C3))

C1 = output2$samples[[1]]
C2 = output2$samples[[2]]
C3 = output2$samples[[3]]
fit_int_p2 = as.data.frame(rbind(C1, C2, C3))

C1 = output3$samples[[1]]
C2 = output3$samples[[2]]
C3 = output3$samples[[3]]
fit_int_p3 = as.data.frame(rbind(C1, C2, C3))

C1 = output4$samples[[1]]
C2 = output4$samples[[2]]
C3 = output4$samples[[3]]
fit_int_p4 = as.data.frame(rbind(C1, C2, C3))

```

# Settlement

## Natal 

```{r}

settlement = output1$mean$eta
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:5)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:5, 5)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 5)%>% 
  subset(., arr != 5)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output1$mean$B %>% rowMeans(),
                 arr = 1:5)

settlement1 = merge(settlement, col_size, by = c("arr"))%>% 
  mutate(Period = "1")

```

```{r}

settlement = output3$mean$eta
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:7)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:7, 7)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 7)%>% 
  subset(., arr != 7)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output3$mean$B %>% rowMeans(),
                 arr = 1:7)

settlement3 = merge(settlement, col_size, by = c("arr")) %>% 
  mutate(Period = "3")

```

```{r}

settlement = output4$mean$eta
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:8)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:8, 8)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 8)%>% 
  subset(., arr != 8)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output4$mean$B %>% rowMeans(),
                 arr = 1:8)

settlement4 = merge(settlement, col_size, by = c("arr")) %>% 
  mutate(Period = "4")

```


```{r}
settlement = rbind(settlement1,
                   settlement3,
                   settlement4)
```


```{r}

natal_plot = ggplot()+
  geom_point(data = settlement, aes(x = mean_B, y = value, color = Period))+
  scale_x_log10()+  # Points de données
  geom_smooth(data = settlement, aes(x = mean_B, y = value, color = Period),method = "lm", se = FALSE)+
  labs(x = "Arrival colony size", y = "Probability of settlement", title = "", subtitle = "", color = "Period")  +
  ggthemes::theme_clean() +
  theme(
    panel.border = element_blank(), # Enlever la bordure du panel
    legend.key = element_blank(),  # Remove legend key background
    legend.background = element_blank(),  # Remove legend background
    axis.title = element_text(size = 11),  # Thicken axis titles
    axis.text = element_text(size = 10),  # Thicken axis text
    axis.line = element_line(size = 2),  # Thicken axis lines
    legend.text = element_text(size = 10),  # Thicken legend text
    legend.title = element_text(size = 12, face = "bold"),
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA),
    axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_color_manual(values = c("1" = "darkblue", 
                                "3" = "pink", 
                                "4" = "darkorange"))

```

## Breeding

```{r}

settlement = output1$mean$nu
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:5)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:5, 5)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 5)%>% 
  subset(., arr != 5)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output1$mean$B %>% rowMeans(),
                 arr = 1:5)

settlement1 = merge(settlement, col_size, by = c("arr"))%>% 
  mutate(Period = "1")

```

```{r}

settlement = output3$mean$nu
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:7)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:7, 7)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 7)%>% 
  subset(., arr != 7)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output3$mean$B %>% rowMeans(),
                 arr = 1:7)

settlement3 = merge(settlement, col_size, by = c("arr")) %>% 
  mutate(Period = "3")

```

```{r}

settlement = output4$mean$nu
for (i in 1:nrow(settlement)){
  settlement[i,i] = 0
}

settlement = settlement / rowSums(settlement)

for (i in 1:nrow(settlement)){
  settlement[i,i] = NA
}

settlement = settlement %>% 
  as.data.frame() %>%
  setNames(as.character(1:8)) %>% 
  gather(key = "arr", value = "value", everything()) %>%
  mutate(dep = rep(1:8, 8)) %>%
  select(dep, arr, value) %>% 
  subset(., dep != arr) %>% 
  subset(., dep != 8)%>% 
  subset(., arr != 8)%>% 
  mutate(dep = as.factor(dep))
  

col_size = data.frame(mean_B = output4$mean$B %>% rowMeans(),
                 arr = 1:8)

settlement4 = merge(settlement, col_size, by = c("arr")) %>% 
  mutate(Period = "4")

```


```{r}
settlement = rbind(settlement1,
                   settlement3,
                   settlement4)
```


```{r}

plot_breeding = ggplot()+
  geom_point(data = settlement, aes(x = mean_B, y = value, color = Period))+
  scale_x_log10()+  # Points de données
  geom_smooth(data = settlement, aes(x = mean_B, y = value, color = Period),method = "lm", se = FALSE)+
  labs(x = "Arrival colony size", y = "Probability of settlement", title = "", subtitle = "", color = "Period")  +
  ggthemes::theme_clean() +
  theme(
    panel.border = element_blank(), # Enlever la bordure du panel
    legend.key = element_blank(),  # Remove legend key background
    legend.background = element_blank(),  # Remove legend background
    axis.title = element_text(size = 11),  # Thicken axis titles
    axis.text = element_text(size = 10),  # Thicken axis text
    axis.line = element_line(size = 2),  # Thicken axis lines
    legend.text = element_text(size = 10),  # Thicken legend text
    legend.title = element_text(size = 12, face = "bold"),
    legend.position =  "none",
    panel.background = element_rect(fill = "transparent", color = NA), 
    plot.background = element_rect(fill = "transparent", color = NA),
    axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_color_manual(values = c("1" = "darkblue", 
                                "3" = "pink", 
                                "4" = "darkorange"))


plot_breeding + natal_plot

```



